version: '3.8'
services:
  web:
    build: .
    ports:
      - "5000:5000"
    command: python web_app.py
  
  gui:
    build: .
    environment:
      - DISPLAY=host.docker.internal:0
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
    command: python gui_app.py